scene.setBackgroundColor(13)
let Love_Giver_Giselle = sprites.create(assets.image`Love Giver Giselle`, SpriteKind.Player)
let Meanie_Marco = sprites.create(assets.image`Meanie Marco`, SpriteKind.Player)
let Cutie_Guy_Christian = sprites.create(assets.image`Cutie Guy Christian`, SpriteKind.Player)
Love_Giver_Giselle.setPosition(124, 25)
Meanie_Marco.setPosition(24, 25)
Cutie_Guy_Christian.setPosition(79, 77)
Love_Giver_Giselle.say("Please accept my love Marco!", 5000)
pause(5000)
Meanie_Marco.say("..uh nah", 5000)
pause(2000)
Cutie_Guy_Christian.say("I'll accept your love Giselle!", 5000)
pause(2000)
Love_Giver_Giselle.say("Uhm ew, go away Christian", 5000)
pause(5000)
let Broken_heart = sprites.create(assets.image`Broken heart`, SpriteKind.Player)
Broken_heart.setPosition(81, 77)
pause(5000)
Broken_heart.destroy()
Cutie_Guy_Christian.destroy()
let Dead_Christian = sprites.create(assets.image`Dead Christian`, SpriteKind.Player)
Dead_Christian.setPosition(83, 77)
